project:
  type: book
  output-dir: docs
  resources:
    - resources/*
book:
  title: "Intro to Coding for Journalists"
  author: "Christian McDonald"
  date: "6/26/2023"
  chapters:
    - href: index.qmd
      text: Home
    - part: start-00-intro.qmd
      chapters:
        - start-01-terminal.qmd
        - start-02-move.qmd
    - setup-01-git.qmd
    - part: git-00-intro.qmd
      chapters:
        - git-01-project.qmd
        - git-02-cycle.qmd
    - part: html-css-00-intro.qmd
      chapters:
        - html-01-practice.qmd
        - html-02-mastery.qmd
        - css-01-practice.qmd
        - css-02-mastery.qmd
    - part: js-00-intro.qmd
      chapters: 
        - js-01-basics.qmd
        - js-02-functions.qmd
        - js-03-objects.qmd
        - js-04-flow-control.qmd
        - js-05-html.qmd
        - js-06-datatables.qmd
    - setup-02-node.qmd
    - part: sass-00-intro.qmd
      chapters: 
        - sass-01-project.qmd
        - sass-02-refactor.qmd
        - sass-03-publish.qmd
    - part: bs-00-intro.qmd
      chapters: 
        - bs-01-components.qmd
        - bs-02-grids.qmd
        - bs-03-cards.qmd
        - bs-04-customize.qmd
        - bs-05-publish.qmd
        - bs-06-mastery.qmd
    - part: sapp-00-intro.qmd
      chapters: 
        - sapp-01-framework.qmd
        - sapp-02-templates.qmd
        - sapp-03-loops.qmd
        - sapp-04-publish.qmd
        - sapp-05-bake-explain.qmd
        - sapp-06-bake-blog.qmd
    - fp-00-intro.qmd
  appendices:
    - a-google-fonts.qmd
    - a-project.qmd
    - a-macos-shell.qmd
    - a-bash-files.qmd
    - a-bash-commands.qmd
    - a-bash-profile.qmd
    - a-git-share.qmd
    - a-git-branch.qmd

format:
  html:
    theme: cosmo
    code-overflow: wrap

