# Terminal

This lesson is a beginner's guide to using **command-line interface** tools for coding and data-journalism. It is designed for students who may have never used a terminal program before but are taking my [Intro to Coding for Journalists](https://github.com/utdata/icj-class) class.

I use a Mac, and there are some differences for Windows users. The first major difference is Windows users have to install Git (and Git Bash, which comes with it) before we can go much further.

## An IMPORTANT note for Windows users

- Windows users need to install a program called **Git** before they proceed with this lesson. Go to [this part of the icj-setting-up lesson](https://github.com/utdata/icj-setting-up/blob/master/windows-01.md#install-git) to follow the directions to install Git, then come return here when the directions tell you to.

## A word about my lessons

For all my lessons I typically put directions for YOU to do in numbered lists:

1. Do this thing.
1. Then do that thing.

Sometimes there is code after or among the the directions, but it is in a code block with a grey background.

1. Do this thing:

```bash
$ command --flag
This is the output
```

1. Then do the next thing.
1. Sometimes the code will be in the bullet item itself, but still in a code block. Do this: `$ command`.

I typically use an unordered bullet list for non-"do" things:

- This is just a note about something
- And this is another

But sometimes I forget and put "do" things in an unordered list. Hopefully you can typically tell when it is a direction or not.

Regular paragraph text such as this one are usually an explanation, background or whatever.

If **something is in bold** or IN ALL CAPS or _in italics for emphasis_ then there is usually a reason why, so pay attention.

> Sometimes I put unimportant but interesting side notes in blockquotes like this.

> **IMPORTANT NOTE**: But sometimes I'll put important notes in these blocktext sections, too. I'll usually say if they are important in bold at the beginning, like this one.

I try to be consistent, but I'm human so sometimes I'm not.
